---
- name: Copy configuration.yaml to HomeAssistant
  copy:
    src: ../data/config/configuration.yaml
    dest: /var/local/homeassistant/.homeassistant/configuration.yaml
    owner: homeassistant
    group: homeassistant
    mode: 0644
  tags:
    - config
    - hass

- name: Set up zwave USB dongle
  blockinfile:
    path: /var/local/homeassistant/.homeassistant/configuration.yaml
    marker: "# {mark} ANSIBLE MANAGED BLOCK #"
    insertafter: "# zwave dongle"
    content: |2
      zwave:
        usb_path: /dev/ttyACM0
  when: inventory_hostname in groups['pi']|default([])
  tags:
    - config
    - hass

- name: Copy groups.yaml to HomeAssistant
  copy:
    src: ../data/config/groups.yaml
    dest: /var/local/homeassistant/.homeassistant/groups.yaml
    owner: homeassistant
    group: homeassistant
    mode: 0644
  tags:
    - config
    - hass

- name: Copy security-zones.yaml to HomeAssistant
  copy:
    src: ../data/config/security-zones.yaml
    dest: /var/local/homeassistant/.homeassistant/security-zones.yaml
    owner: homeassistant
    group: homeassistant
    mode: 0644
  tags:
    - config
    - hass

- name: Copy secrets.yaml to HomeAssistant
  copy:
    src: ../secrets.yaml
    dest: /var/local/homeassistant/.homeassistant/secrets.yaml
    owner: homeassistant
    group: homeassistant
    mode: 0644
  tags:
    - config
    - hass

- name: Copy customize.yaml to HomeAssistant
  copy:
    src: ../data/config/customize.yaml
    dest: /var/local/homeassistant/.homeassistant/customize.yaml
    owner: homeassistant
    group: homeassistant
    mode: 0644
  tags:
    - config
    - hass

- name: Copy automations.yaml to HomeAssistant
  copy:
    src: ../data/config/automations.yaml
    dest: /var/local/homeassistant/.homeassistant/automations.yaml
    owner: homeassistant
    group: homeassistant
    mode: 0644
  tags:
    - config
    - hass

- name: Copy scripts.yaml to HomeAssistant
  copy:
    src: ../data/config/scripts.yaml
    dest: /var/local/homeassistant/.homeassistant/scripts.yaml
    owner: homeassistant
    group: homeassistant
    mode: 0644
  tags:
    - config
    - hass

- name: Restart Home Assistant
  shell: systemctl restart home-assistant.service
  become: yes
  tags:
    - config
    - hass
