---
- name: Copy configuration.yaml to HomeAssistant
  copy:
    src: ../data/config/configuration.yaml
    dest: /var/local/homeassistant/.homeassistant/configuration.yaml
    owner: homeassistant
    group: homeassistant
    mode: 0644
  tags:
    - config

- name: Copy groups.yaml to HomeAssistant
  copy:
    src: ../data/config/groups.yaml
    dest: /var/local/homeassistant/.homeassistant/groups.yaml
    owner: homeassistant
    group: homeassistant
    mode: 0644
  tags:
    - config

- name: Copy security-zones.yaml to HomeAssistant
  copy:
    src: ../data/config/security-zones.yaml
    dest: /var/local/homeassistant/.homeassistant/security-zones.yaml
    owner: homeassistant
    group: homeassistant
    mode: 0644
  tags:
    - config

- name: Copy secrets.yaml to HomeAssistant
  copy:
    src: ../secrets.yaml
    dest: /var/local/homeassistant/.homeassistant/secrets.yaml
    owner: homeassistant
    group: homeassistant
    mode: 0644
  tags:
    - config

- name: Restart Home Assistant
  shell: systemctl restart home-assistant.service
  become: yes
  tags:
    - config
