---
# tasks file for nginx

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes
  tags:
    - nginx

- name: Install nginx
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - nginx
    - git
  tags:
    - nginx

- name: Start nginx
  become: yes
  service:
    name: nginx
    state: started
  tags:
    - nginx

- name: Update nginx config
  template: "src=../templates/default-site.conf dest=/etc/nginx/sites-available/{{server.hostname}} owner=www-data group=www-data mode=0644"
  become: yes
  tags:
    - nginx
    - hass

- name: Add Home Assistant config
  template: "src=../templates/home-assistant.conf dest=/etc/nginx/home-assistant.conf owner=www-data group=www-data mode=0644"
  become: yes
  tags:
    - nginx
    - hass

- name: Enable site
  file: src=/etc/nginx/sites-available/{{server.hostname}} dest=/etc/nginx/sites-enabled/{{server.hostname}} owner=www-data group=www-data state=link
  notify:
    - restart nginx
  become: yes
  tags:
    - nginx
